### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by nacaseven** [Marqasa/overwatch-settings#3]
Is it possible to write a short tutorial for absolute layman? I'm not a programmer and just want to play overwatch. 

What do you mean with "copy the application to your application folder"? The .zip folder? The unzipped folder? Some file?

When I run the command in Terminal it just says "No such file: Settings.app".

**Comment by thinksamwp** [comment]
Download [Overwatch.Settings_0.3.3_aarch64.dmg](https://github.com/Marqasa/overwatch-settings/releases/download/0.3.3/Overwatch.Settings_0.3.3_aarch64.dmg). When you open it you will be able to drag the app to your applications folder. The command should then work!
