### ISSUE TITLE
"Overwatch Settings" is damaged and can't be opened.

### ISSUE THREAD

**Issue by cheesejaguar** [Marqasa/overwatch-settings#4]
Checked both 0.3.3 and 0.3.4, both give the same warning:

<img width="372" alt="image" src="https://github.com/Marqasa/overwatch-settings/assets/4625152/4d14259d-0256-4b3f-a4db-f704021b86e8">

macOS Sonoma 14.0

**Comment by thinksamwp** [comment]
Did you run the terminal command in step 3 of the installation instructions?
